### PR TITLE
Use `RequestRecordingButton` to link to recording page

### PR DESCRIPTION
**Pull request by dabbler0**

### CODE REVIEW

**Comment by cainlevy** [comment]
@dabbler0 might want to try a `git rebase -i` to filter out the extra commits from `main` so the changeset is easier to see

**Comment by dabbler0** [comment]
> @dabbler0 might want to try a `git rebase -i` to filter out the extra commits from `main` so the changeset is easier to see

I may have gotten myself into a tangle here because the main substance of this branch is a merge commit; I'm not actually sure how to just the "manually resolved" portion of the merge and not the automatically-merged rest of it. The two files that were not automatically merged were [src/components/SearchMeetings/SearchMeetingsTable.tsx](https://github.com/Ameelio/connect-doc-client/pull/450/commits/d7f16e5cdd1e3e0736ac30f449876ccf736679d4#diff-2dcd1696d3171000b32479c7a675cebe9bab3c31aab374b993b8c331f1134d2a) (see lines 205/182) and [src/components/RequestRecordingButton.tsx](https://github.com/Ameelio/connect-doc-client/pull/450/commits/d7f16e5cdd1e3e0736ac30f449876ccf736679d4#diff-25c05e842e432a01067f7b5b72ffb3fe52b67981dc5fea5bd3eb0110e8aaefde) (see line 54).

**Comment by cainlevy** [comment]
I would probably create a new branch from Ty's and just copy those files over with the clipboard or `git checkout branch:path/to/file`.

**Comment by dabbler0** [comment]
The changes also depend on most of the changes from a previously merged PR for the `RequestRecordingButton`, so a lot of these commits are necessary. I think the best thing might be for Ty to do a naive merge from main first on the base branch, and then I can make changes based on that merged copy.

**Comment by dabbler0** [comment]
I'll re-make this PR based on the merged version of Ty's branch.

**Pull request closed without merging**
