### PR TITLE
Sc 4694

### PR DESCRIPTION
**Pull request by enrjp**
I couldn't remove all references just yet as we will need to remove from the API and re-import the updated schema in order to remove absolutely all references.

### CODE REVIEW

**Comment by cainlevy** [comment]
@enrjp would you prefer to move this to draft until we reprioritize the work, or start fresh when we're not blocked by connect-mobile?

**Comment by enrjp** [comment]
I'd prefer to start fresh actually - I'll close this PR but leave the branch?

**Comment by cainlevy** [comment]
@enrjp sgtm. same for the other pull requests?

**Comment by enrjp** [comment]
Yep! I'll close those and add a comment indicating my intent to start fresh

**Comment by enrjp** [comment]
Closing pull request, will start fresh once the updated API has been released

**Pull request closed without merging**
